#!/usr/bin/env bash


new_desktop() {
    TargetFile="$1"
    Name="$2"
    Comment="$3"

    Category="$4"

    FlatName=$(echo "$Name" | tr '[:upper:]' '[:lower:]' | tr ' !@#$%^&*()=_+[]{};,./<>?`~' '-')

    if [ -z "$Category" ] ; then
        Category=""
    fi
    read -r -d '' DesktopEntry <<EOF
[Desktop Entry]
Name=$Name
Comment=$Comment
Exec=$TargetFile
Icon=$HOME/bin/launchers/$(basename "$TargetFile").png
Type=Application
Version=1.0
Categories=$Category;
Terminal=false
StartupWMClass=$FlatName
StartupNotify=true
EOF
    echo "$DesktopEntry" > "$HOME/bin/launchers/$(basename "$TargetFile").desktop"
    chmod +x "$HOME/bin/launchers/$(basename "$TargetFile").desktop"
    mkdir -p "$HOME/.local/share/applications"
    ln -sf "$HOME/bin/launchers/$(basename "$TargetFile").desktop" "$HOME/.local/share/applications"
}